#!/bin/bash
set -euo pipefail

if chronic systemctl is-system-running --wait; then
  exit 0
fi

# Work around bug in nvidia template and cosmic variant
for i in nvidia-cdi-refresh.path nvidia-cdi-refresh.service systemd-vconsole-setup.service; do
  if systemctl is-failed "$i"; then
    sudo systemctl reset-failed "$i"
    if chronic systemctl is-system-running --wait; then
      exit 0
    fi
  fi
done

systemctl --failed --no-legend --no-pager --plain |
  while read -r unit _; do
    if [ -n "$unit" ]; then
      echo "--- $unit ---"
      systemctl status "$unit" --no-pager --no-legend || true
    fi
  done
exit 1
